services:
  postgres:
    image: postgres:latest
    container_name: SensorManagementDBContainer
    environment:
      POSTGRES_USER: sensor_management_user
      POSTGRES_PASSWORD: Postgres@Radix
      POSTGRES_DB: SensorManagementDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network

volumes:
  postgres_data:

networks: 
  postgres-network:
    external: true